version: '3'

services:
  db:
    image: postgres:10
  rest-api:
    build: .
    tty: true
    command: bash
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
